sudo: false
language: elixir
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.5
otp_release:
  - 17.5
  - 18.0
  - 18.1
  - 18.2
script: mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
