sudo: false
language: elixir
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.4
  - 1.4.4
otp_release:
  - 18.3
  - 19.3
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
matrix:
  exclude:
  - elixir: 1.1.1
    otp_release: 19.3

